name: EpicGames Freebies Claimer
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 18 * * 4"

jobs:
  epicfree:
    name: Claim Freebies
    runs-on: ubuntu-latest
    steps:
      - name: Setup data folder
        run: mkdir -p "${GITHUB_WORKSPACE}/data"

      - name: Setup authentication config file
        env:
          EPIC_GAMES_AUTH_JSON: ${{ secrets.EPIC_GAMES_AUTH_JSON }}
        run: echo "${EPIC_GAMES_AUTH_JSON}" > ${GITHUB_WORKSPACE}/data/device_auths.json

      - name: Setup config file
        env:
          EPIC_GAMES_CONFIG_JSON: ${{ secrets.EPIC_GAMES_CONFIG_JSON }}
        run: echo "${EPIC_GAMES_CONFIG_JSON}" > ${GITHUB_WORKSPACE}/data/config.json

      - name: Claim
        run: docker run --name epicfree --rm --pull always --volume "${GITHUB_WORKSPACE}/data:/app/data" ghcr.io/jackblk/epicgames-freebies-claimer:latest
